### ISSUE TITLE
Move from isomorphic-fetch to cross-fetch

### ISSUE THREAD

**Issue by TPXP** [serverless/platform-sdk#93]
Hello,

The isomorphic-fetch has not been updated in 5 years, and as a consequence relies on an old version of `node-fetch`. This causes an issue when trying to use modes that define fetch globals if needed in a function ran with `serverless-offline` (as the globals it wants to define are already defined). - see https://github.com/sindresorhus/ky/issues/258 for example

[Cross-fetch](https://www.npmjs.com/package/cross-fetch) seems to be a good up-to-date substitute.

Similar to https://github.com/serverless/enterprise-plugin/issues/448

**Comment by medikoo** [comment]
@TPXP This package is deprecated, and in few months it should be not part of `serverless` dependencies. Still PR that replaces `isomorphic-fetch` is very welcome.

**Comment by TPXP** [comment]
Thanks for your feedback, I opened #95 and #94
