### ISSUE TITLE
npm audit security warning 1556

### ISSUE THREAD

**Issue by andrewspinks** [serverless/platform-sdk#96]
npm audit is reporting a security warning as the last released version of the sdk was still using isomorphic-fetch, which depends on an old version of node-fetch with a reported security vulnerability.

It seems like the isomorphic-fetch dep has been removed, so I suspect a new release will fix the issue.

**Comment by medikoo** [comment]
@andrewspinks thanks for pointined. Indeed we didn't introduce a patch release after dropping `isomorphic-fetch`.

v2.3.2 was published just now, and it'll be ensured to be picked with next version of a Framework

**Comment by andrewspinks** [comment]
Thank you!
